
<?php 
    $_product = $this->getProduct();
    $helper = $this->helper('catalog/output');
   // $zoomhelper       = Mage::helper('daff_zoom');
 //echo "value is".$value=  Mage::getStoreConfig('zoom/all_settings/lens_width');
 $lensWidth= intval(Mage::getStoreConfig('zoom/all_settings/lens_width'));
  $lensBordercolor     = trim(Mage::getStoreConfig('zoom/all_settings/lens_border_color'));
   $borderSize     = intval(Mage::getStoreConfig('zoom/all_settings/lens_border_size'));
?>

<?php 
if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
<img id="image" src="" style="display:none"/>
    <?php
        $_img = '<img id="" class="image_05" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" height="200px" width="250px"/>';
        echo $helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<p class="zoom-notice" id="track_hint"></p>
<div class="zoom">

    <div id="track">
    </div>

</div>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
//]]>
</script>

<?php endif; 
?>

<?php if (count($this->getGalleryImages()) > 0):?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="#" rel="#mies<?php echo $i?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
               <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>"alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" onClick="imgChange('<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) ?>')"/>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>

<?php endif; ?>

           
	<script type="text/javascript" language="javascript">
              jQuery.noConflict();
              function imgChange(path){
		jQuery(".image_05").attr("src", path);
		jQuery(".undefined").css("background-image",'url('+path+')');
                jQuery(".product-image img:last")   .attr("src", path);
            //jQuery(".product-image img:nth-child(2)").attr("src", path);
}
               var lenswidth = "<?php echo $lensWidth; ?>";
               var lensbordercolor="<?php echo $lensBordercolor; ?>";
                var borderSize="<?php echo $borderSize;?>";
		jQuery(function ($) {
                        $(".image_05").imageLens({ lensSize:lenswidth,borderColor:lensbordercolor,borderSize:borderSize});
		});	
	</script>
